[package]
name = "maptools"
version = "0.1.0"
edition = "2021"
authors = ["Stephen Catsamas <seca8194@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "maptoolslib"
crate-type = ["dylib"]


[dependencies.cpython]
version = "0.7.0"
features = ["extension-module"]

[dependencies.wgpu]
version  = "0.11"
features = ["spirv"]

[dependencies]
cmake = "0.1.46"
image = "0.23"
raw-window-handle = "0.3"
winit = "0.25"
shaderc = "0.7"
cgmath = "0.18"
pollster = "0.2"

[build-dependencies]
chrono = "0.4.19"