[package]
name = "maptools"
version = "0.1.0"
edition = "2021"
authors = ["Stephen Catsamas <seca8194@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "maptoolslib"
crate-type = ["dylib"]


[dependencies.cpython]
version = "0.7.0"
features = ["extension-module"]

[dependencies.glium]
version = "0.31.0"

[build-dependencies]
chrono = "0.4.19"